In [ ]:
import pandas as pd
import numpy as np

# 1. LOADING AND COMBINING DATASETS

In [ ]:
chicago_df = pd.read_csv('Chicago_listings (1).csv')
nola_df = pd.read_csv('New Orleans_listings.csv')

In [ ]:
# Chicago Listings data first look
chicago_df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2384,Hyde Park: 5 minute walk to Obama Presidential...,2613.0,1.462506e+18,Rebecca,NaN,Hyde Park,41.78790,-87.58780,Private room,171.0,2.0,268,2026-06-08,1.92,1.0,310,14,R17000015609
1,7126,Tiny Studio Apartment 94 Walk Score,17928.0,1.462507e+18,Sarah,NaN,West Town,41.90166,-87.68021,Entire home/apt,112.0,2.0,626,2026-05-25,3.03,1.0,247,43,R26000138446
2,10945,The Biddle House (#1),33004.0,1.462507e+18,Elizabeth,NaN,Lincoln Park,41.91196,-87.63981,Entire home/apt,280.0,4.0,152,2026-06-06,1.03,6.0,283,29,2209984
3,12140,Lincoln Park Guest House,46734.0,1.462508e+18,Shar And Robert,NaN,Lincoln Park,41.92357,-87.64947,Private room,422.0,2.0,21,2026-06-21,0.16,1.0,136,3,2398451
4,71930,"Rest, Relax and Explore",334241.0,1.462511e+18,Michael And Veronica,NaN,West Town,41.89615,-87.67934,Private room,109.0,3.0,158,2026-06-02,0.86,1.0,326,22,R23000108832

In [ ]:
chicago_df.shape

(8704, 19)

In [ ]:
#New Orleans Listings data first look
nola_df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,19091,Fully Furnished Cozy Apartment,72880.0,1.462508e+18,John,NaN,Leonidas,29.96100,-90.11950,Entire home/apt,137.0,1.0,542,2026-05-30,2.75,1.0,306,38,"25-NSTR-11772, 25-OSTR-11151"
1,71624,Ravenwood Manor (Historic Bywater),367223.0,1.462517e+18,Susan,NaN,Bywater,29.96153,-90.04364,Entire home/apt,166.0,30.0,316,2025-05-07,1.69,1.0,365,0,"21-RSTR-18609, 22-OSTR-20720"
2,74498,Maison Marais 1,391462.0,1.462517e+18,Georgia,NaN,St. Roch,29.96986,-90.05172,Entire home/apt,175.0,3.0,689,2026-05-19,3.71,3.0,231,29,23-XSTR-13082
3,79536,FeelAtHomeInNewOrleans-PrivateApt,428362.0,1.462518e+18,Miriam,NaN,Seventh Ward,29.97803,-90.07450,Entire home/apt,NaN,3.0,853,2026-06-12,4.63,1.0,0,72,"23-NSTR-15067, 25-OSTR-41594"
4,79609,Bywater's Original & Finest,428909.0,1.462512e+18,Stephen,NaN,St. Claude,29.96448,-90.03667,Entire home/apt,63.0,30.0,505,2025-03-05,2.72,1.0,198,0,"23-ISTR-02823, 23-OSTR-02823"

In [ ]:
nola_df.shape

(7254, 19)

In [ ]:
# Adding a 'City' column to each dataframe before combining
chicago_df['city'] = 'Chicago'
nola_df['city'] = 'New Orleans'

In [ ]:
# Combining both datasets vertically
df = pd.concat([chicago_df, nola_df], ignore_index=True)
df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city
0,2384,Hyde Park: 5 minute walk to Obama Presidential...,2613.0,1.462506e+18,Rebecca,NaN,Hyde Park,41.78790,-87.58780,Private room,171.0,2.0,268,2026-06-08,1.92,1.0,310,14,R17000015609,Chicago
1,7126,Tiny Studio Apartment 94 Walk Score,17928.0,1.462507e+18,Sarah,NaN,West Town,41.90166,-87.68021,Entire home/apt,112.0,2.0,626,2026-05-25,3.03,1.0,247,43,R26000138446,Chicago
2,10945,The Biddle House (#1),33004.0,1.462507e+18,Elizabeth,NaN,Lincoln Park,41.91196,-87.63981,Entire home/apt,280.0,4.0,152,2026-06-06,1.03,6.0,283,29,2209984,Chicago
3,12140,Lincoln Park Guest House,46734.0,1.462508e+18,Shar And Robert,NaN,Lincoln Park,41.92357,-87.64947,Private room,422.0,2.0,21,2026-06-21,0.16,1.0,136,3,2398451,Chicago
4,71930,"Rest, Relax and Explore",334241.0,1.462511e+18,Michael And Veronica,NaN,West Town,41.89615,-87.67934,Private room,109.0,3.0,158,2026-06-02,0.86,1.0,326,22,R23000108832,Chicago

In [ ]:
df.shape

(15958, 20)

# 2. DATA CLEANING & HANDLING MISSING VALUES

In [ ]:
# Drop rows where critical operational or location data is missing
df = df.dropna(subset=['price', 'latitude', 'longitude', 'host_id'])

In [ ]:
# The 'neighbourhood_group' is completely empty in this dataset, so we drop it
if 'neighbourhood_group' in df.columns and df['neighbourhood_group'].isnull().all():
    df = df.drop(columns=['neighbourhood_group'])

In [ ]:
# Handle missing reviews data
# A missing 'reviews_per_month' implies 0 reviews have been left
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)
df['last_review'] = df['last_review'].fillna('No Reviews')

In [ ]:
# Handle missing text/categorical data
df['host_name'] = df['host_name'].fillna('Unknown Host')
df['license'] = df['license'].fillna('Unlicensed/Exempt')

In [ ]:
# Remove duplicate listings if they were accidentally scraped twice
df = df.drop_duplicates(subset=['id'])

# 3. TEXT STANDARDIZATION (Group and Replace Logic)

In [ ]:
df['neighbourhood'] = df['neighbourhood'].astype(str).str.title().str.strip()
df['room_type'] = df['room_type'].astype(str).str.title().str.strip()

# 4. DATA TRANSFORMATION

In [ ]:
# A. Categorize Price (Pricing Analysis)
def categorize_price(price):
    if price < 75:
        return 'Budget (<$75)'
    elif price <= 200:
        return 'Standard ($75-$200)'
    elif price <= 500:
        return 'Premium ($201-$500)'
    else:
        return 'Luxury (>$500)'

df['price_tier'] = df['price'].apply(categorize_price)

In [ ]:
# B. Host Type Classification (Host Analysis)
# Group by host_id to count how many listings a host operates total across the dataset
df['total_host_listings'] = df.groupby('host_id')['id'].transform('count')

In [ ]:
# Classify host behavior
df['host_type'] = np.where(
    df['total_host_listings'] >= 3,
    'Commercial (3+ Listings)',
    'Casual (1-2 Listings)'
)

In [ ]:
# C. Booking Availability Status (Property Analysis)
def availability_status(days):
    if days == 0:
        return 'Fully Booked / Inactive'
    elif days < 90:
        return 'Low Availability (< 90 days)'
    elif days < 270:
        return 'Medium Availability'
    else:
        return 'High Availability (> 270 days)'

df['availability_tier'] = df['availability_365'].apply(availability_status)

In [ ]:
# D. Engagement Level (Proxy for Popularity)
def engagement_level(reviews):
    if reviews == 0:
        return 'No Reviews'
    elif reviews <= 10:
        return 'Low Engagement'
    elif reviews <= 50:
        return 'Moderate Engagement'
    else:
        return 'High Engagement'

df['engagement_tier'] = df['number_of_reviews'].apply(engagement_level)

In [ ]:
df.describe()

,id,host_id,host_profile_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,total_host_listings
count,1.402100e+04,1.402100e+04,1.393400e+04,14021.000000,14021.000000,14021.000000,14012.000000,14021.000000,14021.000000,14021.000000,14021.000000,14021.000000,14021.000000
mean,8.058670e+17,4.188556e+15,1.473817e+18,36.426788,-88.766424,294.401041,12.114259,69.489979,1.537191,15.772698,240.758576,14.570073,15.648741
std,6.251756e+17,8.373496e+16,3.190319e+16,5.945503,1.200798,377.461934,19.692747,107.981442,1.823630,26.793649,102.351479,22.026499,26.603893
min,2.384000e+03,2.613000e+03,1.462506e+18,29.897680,-90.135521,3.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,4.603658e+07,4.818777e+07,1.463087e+18,29.958889,-90.071320,128.000000,2.000000,3.000000,0.190000,1.000000,160.000000,0.000000,1.000000
50%,9.355625e+17,1.866517e+08,1.468177e+18,41.782470,-87.729317,208.000000,2.000000,27.000000,1.130000,4.000000,269.000000,7.000000,4.000000
75%,1.373888e+18,4.574382e+08,1.470030e+18,41.899090,-87.655537,340.000000,30.000000,94.000000,2.410000,17.000000,328.000000,24.000000,16.000000
max,1.714532e+18,1.710597e+18,1.710597e+18,42.021360,-87.528420,9501.000000,365.000000,2179.000000,77.090000,436.000000,365.000000,1231.000000,127.000000

In [ ]:
df.describe(include=['O'])

,name,host_name,neighbourhood,room_type,last_review,license,city,price_tier,host_type,availability_tier,engagement_tier
count,14021,14021,14021,14021,14021,14021,14021,14021,14021,14021,14021
unique,13636,3095,146,4,1180,7083,2,4,2,4,4
top,La Belle Maison Resort| 1BR Resort Suite,David,Central Business District,Entire Home/Apt,No Reviews,Unlicensed/Exempt,Chicago,Premium ($201-$500),Commercial (3+ Listings),High Availability (> 270 days),High Engagement
freq,20,173,1298,10926,2180,3252,7601,5580,8025,6941,5324

In [ ]:
df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood,latitude,longitude,room_type,price,...,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city,price_tier,total_host_listings,host_type,availability_tier,engagement_tier
0,2384,Hyde Park: 5 minute walk to Obama Presidential...,2613.0,1.462506e+18,Rebecca,Hyde Park,41.78790,-87.58780,Private Room,171.0,...,1.0,310,14,R17000015609,Chicago,Standard ($75-$200),1,Casual (1-2 Listings),High Availability (> 270 days),High Engagement
1,7126,Tiny Studio Apartment 94 Walk Score,17928.0,1.462507e+18,Sarah,West Town,41.90166,-87.68021,Entire Home/Apt,112.0,...,1.0,247,43,R26000138446,Chicago,Standard ($75-$200),1,Casual (1-2 Listings),Medium Availability,High Engagement
2,10945,The Biddle House (#1),33004.0,1.462507e+18,Elizabeth,Lincoln Park,41.91196,-87.63981,Entire Home/Apt,280.0,...,6.0,283,29,2209984,Chicago,Premium ($201-$500),6,Commercial (3+ Listings),High Availability (> 270 days),High Engagement
3,12140,Lincoln Park Guest House,46734.0,1.462508e+18,Shar And Robert,Lincoln Park,41.92357,-87.64947,Private Room,422.0,...,1.0,136,3,2398451,Chicago,Premium ($201-$500),1,Casual (1-2 Listings),Medium Availability,Moderate Engagement
4,71930,"Rest, Relax and Explore",334241.0,1.462511e+18,Michael And Veronica,West Town,41.89615,-87.67934,Private Room,109.0,...,1.0,326,22,R23000108832,Chicago,Standard ($75-$200),1,Casual (1-2 Listings),High Availability (> 270 days),High Engagement

In [ ]:
# 5. EXPORT FINAL DATASET
export_filename = 'Cleaned_Airbnb_Chicago_NewOrleans.csv'
df.to_csv(export_filename, index=False)

In [ ]:
print(f"Data cleaning complete! Final shape: {df.shape}")
print(f"File successfully saved as: {export_filename}")

Data cleaning complete! Final shape: (14021, 24)
File successfully saved as: Cleaned_Airbnb_Chicago_NewOrleans.csv

In [ ]:
df.columns

Index(['id', 'name', 'host_id', 'host_profile_id', 'host_name',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license', 'city',
       'price_tier', 'total_host_listings', 'host_type', 'availability_tier',
       'engagement_tier'],
      dtype='object')

In [ ]:
df['city'].unique()

array(['Chicago', 'New Orleans'], dtype=object)